### ISSUE TITLE
RhinoCommon 5 and RhinoCommon 6 have different representations of the objects, although the API is the same

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Rhinoceros_Toolkit#137]
#### Description:

Thanks to @kThorsager, who discovered this issue while dealing with `NurbsCurve`s: #135 and #136.

We found that `Rhino.Geometry.ControlPoints`, whilst keeping the same API, it asks for a different representation between RhinoCommon v5 and RhinoCommon v6. This is explicit in their documentation as shown below:  

**Rhino 5**  
![ED4D808D](https://user-images.githubusercontent.com/26899347/73933404-48cecb00-48d4-11ea-9774-a2f8e88e4d05.PNG)

**Rhino 6**  
![image](https://user-images.githubusercontent.com/26899347/73935876-78340680-48d9-11ea-8d5e-a7ac88c90a07.png)

@kThorsager has gone through the v5 documentation and found the following test script:
https://developer.rhino3d.com/5/api/RhinoCommonWin/html/M_Rhino_Geometry_Collections_NurbsCurvePointList_SetPoint_2.htm#ID0EBBBBA_tab1

If we run this script in the two versions of rhino, we get different behaviours:  

**Rhino 5**  
![4C4DEF23](https://user-images.githubusercontent.com/26899347/73939884-48d5c780-48e2-11ea-87ad-0bd25793cf7f.PNG)

**Rhino 6**
![47A816C8](https://user-images.githubusercontent.com/26899347/73939880-483d3100-48e2-11ea-985d-519ecc9a6368.PNG)

We need to test all the other `Convert` methods to understand how spread is the problem.
For the moment, I would advice against using the BHoM with Rhinoceros 6, until we have solved this issue.

The ultimate goal for this issue is to provide full compatibility for Rhinoceros 6.

#### Test file(s):

You can use the test file in #135 

@al-fisher @alelom FYI

**Comment by pawelbaran** [comment]
Just curious: we've spotted that some curves internalized in GH under Rhino5 were flipped when the same script is opened in Rhino6. Is that something that could relate this issue by any means?

**Comment by epignatelli** [comment]
It is very probable that the issue is related, in my opinion, but I can't be 100% sure.
