### ISSUE TITLE
Rhino_Toolkit: sporadic crashes with system memory violation

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Rhinoceros_Toolkit#169]
#### Description:

Very unsure on what's happening since I've only found it in a large project script, but it does completely crash Rhino, which is annoying.

This is where it crashes with this exception, but the actually crash happens in the exteranl code, so suspect we need better checks on what we send in or similar.

![image](https://user-images.githubusercontent.com/53530468/87776540-dae1e480-c81f-11ea-95ea-da0d29db933c.png)

Sorry for the extremely unclear issue, but this is all I know

#### Steps to reproduce:

I have no idea, it's barely consistent

#### Expected behaviour:

Don't crash

**Comment by epignatelli** [comment]
Uhm, are you able to provide a minimal example?

I can guess what is unsafely accessed, but that's just a guess - the bug may still be there.

**Comment by kThorsager** [comment]
I have a big example,
It has occurred while moving the small rectangles about
https://burohappold.sharepoint.com/:f:/s/BHoM/EoqiBj-1bDhCmYBN_sD_NzQBxlNRQgNx2R4VqIJPfWzIkw?e=F8NALh

**Comment by epignatelli** [comment]
I can't reproduce on Rhino 6 actually. 

Does it happen also with preview disabled?

**Comment by kThorsager** [comment]
I'm on Rhino 6,

And yes when disabled through here (unsure of if there are other ways)
![image](https://user-images.githubusercontent.com/53530468/87782122-d7535b00-c829-11ea-99b3-fafd99b0064b.png)

Will try a fresh alpha install and try again

**Comment by kThorsager** [comment]
Was positively convinced that nothing I've built was used in this script, but am myself unable to recreate now so 🤷‍♂️

Thanks for you patience @epignatelli

**Comment by epignatelli** [comment]
No worries at all @kThorsager ! Let's see if anyone else raises the issue as well - I'll investigate.
